config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'carts/show'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'up' => 'rails/health#show', as: :rails_health_check

  get '/pages/:title', to: 'static_pages#show', as: 'static_page'

  root 'home#index'

  resource :cart, only: [:show] do
    post 'add_product/:product_id', action: :add_product, as: 'add_product'
    patch 'update_quantity/:id', action: :update_quantity, as: 'update_quantity'
    delete 'remove_product/:id', action: :remove_product, as: 'remove_product'

    get 'checkout', on: :collection
    post 'process_checkout', to: 'carts#process_checkout'
  end

  resources :orders, only: [:index, :show]

  get 'products/on_sale', to: 'products#on_sale', as: 'on_sale_products'
  get 'products/new_products', to: 'products#new_products', as: 'new_products'
  get 'products', to: 'products#index', as: 'products'
  get 'products/category/:id', to: 'products#by_category', as: 'products_by_category'
  get 'products/search', to: 'products#search', as: 'search_products'
  get 'products/:id', to: 'products#show', as: 'product'
end

app/views/shared/_navbar.html.erb
 <nav>
      <ul>
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'About', static_page_path(title: 'About') %></li>
        <li><%= link_to 'Contact', static_page_path(title: 'Contact') %></li>
        <li><%= link_to 'All Products', products_path %></li>
        <li><%= link_to 'My orders', orders_path, class: 'btn btn-secondary' %></li>
        <li><%= link_to 'Cart', cart_path, class: 'btn btn-primary' %></li>
        <% unless user_signed_in? %>
          <li><%= link_to "Sign in", new_user_session_path, class: "btn btn-primary" %></li>
        <% end %>
        <% if user_signed_in? %>
          <li><%= link_to 'Logout', destroy_user_session_path, data: { turbo_method: :delete } %></li>
          <li>
            <% if current_user.avatar.attached? %>
            <%= image_tag(current_user.avatar.variant(resize_to_fill: [60, 40]), alt: 'Avatar', class: 'avatar') if current_user.avatar.attached? %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </nav>