config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'carts/show'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'up' => 'rails/health#show', as: :rails_health_check

  get '/pages/:title', to: 'static_pages#show', as: 'static_page'

  root 'home#index'

  resource :cart, only: [:show] do
    post 'add_product/:product_id', action: :add_product, as: 'add_product'
    patch 'update_quantity/:id', action: :update_quantity, as: 'update_quantity'
    delete 'remove_product/:id', action: :remove_product, as: 'remove_product'

    get 'checkout', on: :collection
    post 'process_checkout', to: 'carts#process_checkout'
  end

  resources :orders, only: [:index, :show]

  get 'products/on_sale', to: 'products#on_sale', as: 'on_sale_products'
  get 'products/new_products', to: 'products#new_products', as: 'new_products'
  get 'products', to: 'products#index', as: 'products'
  get 'products/category/:id', to: 'products#by_category', as: 'products_by_category'
  get 'products/search', to: 'products#search', as: 'search_products'
  get 'products/:id', to: 'products#show', as: 'product'
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

# CartsController manages the shopping cart functionality for users,
# allowing them to view, add, update, and remove products in their cart.
# It also handles the checkout process where users can finalize their order.
class CartsController < ApplicationController
  # Ensure the user is authenticated before accessing any cart actions.
  before_action :authenticate_user!

  # Displays the current order (shopping cart) for the logged-in user.
  def show
    @order = current_order
  end

  # Adds a product to the cart. If the product is already in the cart,
  # it increases the quantity. A maximum of 5 units per product is allowed.
  # Redirects with an alert if the quantity exceeds the limit.
  def add_product
    product = Product.find(params[:product_id])
    @order = current_order
    quantity = params[:quantity].to_i

    if quantity > 5
      redirect_to product_path(product), alert: t("carts.alerts.cannot_add_more_than_5")
      return
    end

    @order_detail = @order.order_details.find_or_initialize_by(product:)

    new_quantity = @order_detail.new_record? ? quantity : @order_detail.quantity + quantity

    if new_quantity > 5
      redirect_to product_path(product), alert: t("carts.alerts.cannot_add_more_than_5")
    else
      @order_detail.quantity = new_quantity
      @order_detail.unit_price = product.price
      @order_detail.save
      @order.save

      redirect_to cart_path, notice: t("carts.alerts.product_added")
    end
  end

  # Updates the quantity of a specific product in the cart.
  # Ensures that the quantity does not exceed 5 units.
  def update_quantity
    @order_detail = OrderDetail.find(params[:id])
    new_quantity = params[:order_detail][:quantity].to_i

    if new_quantity > 5
      redirect_to cart_path, alert: t("carts.alerts.cannot_have_more_than_5")
      return
    end

    if @order_detail.update(quantity: new_quantity)
      @order_detail.order.save
      redirect_to cart_path, notice: t("carts.alerts.quantity_updated")
    else
      redirect_to cart_path, alert: t("carts.alerts.error_updating_quantity")
    end
  end

  # Removes a product from the cart.
  def remove_product
    @order_detail = OrderDetail.find(params[:id])
    @order_detail.destroy
    @order_detail.order.save

    redirect_to cart_path, notice: t("carts.alerts.product_removed")
  end

  # Initiates the checkout process by ensuring the cart is not empty.
  # Redirects with an alert if the cart is empty.
  def checkout
    @order = current_order

    return unless @order.order_details.empty?

    redirect_to cart_path, alert: t("carts.alerts.cart_empty")
  end

  # Finalizes the checkout process, completing the order and updating user details
  # if necessary. Clears the current order session upon successful checkout.
  def process_checkout
    @order = current_order
    @order.attributes = order_params

    current_user.update(address: @order.address, province: @order.province) if current_user.address.blank? || current_user.province.blank?

    @order.status = "completed"
    if @order.save
      session[:order_id] = nil # Clear the order session
      redirect_to root_path, notice: t("carts.alerts.order_completed")
    else
      render :checkout
    end
  end

  private

  # Retrieves the current order for the user from the session,
  # or creates a new order if none exists.
  def current_order
    if session[:order_id].present?
      begin
        Order.find(session[:order_id])
      rescue ActiveRecord::RecordNotFound
        create_new_order
      end
    else
      create_new_order
    end
  end

  # Creates a new order with default attributes for the current user
  # and saves it without validation.
  def create_new_order
    order = Order.new(user: current_user, date: Time.zone.today, status: "pending", province: current_user.province)
    order.save(validate: false)
    session[:order_id] = order.id
    order
  end

  # Strong parameters for order updates, allowing nested attributes for order details.
  def order_params
    params.require(:order).permit(:address, :province_id, order_details_attributes: %i[id quantity])
  end
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

# The CartsHelper module is intended to contain helper methods related to
# managing and displaying shopping cart functionality within views.
# These methods can simplify the rendering of cart details, such as
# displaying cart summaries, calculating totals, or formatting item lists.
#
# Example usage might include methods for formatting cart item details,
# displaying cart item counts, or generating links related to cart actions.
module CartsHelper
end

app/views/carts/checkout.html.erb
<h1>Checkout</h1>

<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

<%= form_with model: @order, url: process_checkout_cart_path, method: :post, local: true do |f| %>
  <div>
    <%= f.label :address %>
    <%= f.text_field :address, value: @order.address || current_user.address %>
  </div>
  <div>
    <%= f.label :province_id, 'Province' %>
    <%= f.collection_select :province_id, Province.all, :id, :name, selected: @order.province_id || current_user.province_id %>
  </div>
  <h2>Order Details</h2>
  <ul>
    <% @order.order_details.each do |detail| %>
      <li>
        <%= detail.product.name %> - Quantity: <%= detail.quantity %> - Unit Price: <%= number_to_currency(detail.unit_price) %>
      </li>
    <% end %>
  </ul>
  <p>Subtotal: <%= number_to_currency(@order.order_details.sum { |detail| detail.quantity * detail.unit_price }) %></p>
  <p>Taxes: <%= number_to_currency(@order.taxes) %></p>
  <p>Total: <%= number_to_currency(@order.calculate_total) %></p>
  <%= f.submit 'Complete Order' %>
<% end %>

app/views/carts/show.html.erb
<h1>Shopping cart</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Unitary price</th>
      <th>quantity</th>
      <th>Subtotal</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @order.order_details.each do |order_detail| %>
      <tr>
        <td><%= order_detail.product.name %></td>
        <td><%= number_to_currency(order_detail.unit_price) %></td>
        <td>
          <%= form_with model: order_detail, url: update_quantity_cart_path(order_detail.id), method: :patch, local: true do |form| %>
            <%= form.number_field :quantity, value: order_detail.quantity, min: 1, max: 5 %>
            <%= form.submit 'Update' %>
          <% end %>
        </td>
        <td><%= number_to_currency(order_detail.quantity * order_detail.unit_price) %></td>
        <td><%= link_to 'remove', remove_product_cart_path(order_detail.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div>
  <strong>Total: <%= number_to_currency(@order.calculate_total) %></strong>
</div>

<%= link_to 'Keep browsing', root_path %>
<%= link_to 'Checkout', checkout_cart_path, class: 'button' %>