config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'carts/show'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'up' => 'rails/health#show', as: :rails_health_check

  get '/pages/:title', to: 'static_pages#show', as: 'static_page'

  root 'home#index'

  resource :cart, only: [:show] do
    post 'add_product/:product_id', action: :add_product, as: 'add_product'
    patch 'update_quantity/:id', action: :update_quantity, as: 'update_quantity'
    delete 'remove_product/:id', action: :remove_product, as: 'remove_product'

    get 'checkout', on: :collection
    post 'process_checkout', to: 'carts#process_checkout'
  end

  resources :orders, only: [:index, :show]

  get 'products/on_sale', to: 'products#on_sale', as: 'on_sale_products'
  get 'products/new_products', to: 'products#new_products', as: 'new_products'
  get 'products', to: 'products#index', as: 'products'
  get 'products/category/:id', to: 'products#by_category', as: 'products_by_category'
  get 'products/search', to: 'products#search', as: 'search_products'
  get 'products/:id', to: 'products#show', as: 'product'
end

app/models/product.rb
# frozen_string_literal: true

# Product represents an item available for purchase, including its details such as
# name, description, price, stock, and associated images. Each product belongs to
# a category and can be part of multiple orders through order details.
#
# Associations:
# - `belongs_to :category`: Establishes a one-to-one relationship where each product
#   is associated with a single category.
# - `has_many :order_details`: Indicates that each product can have multiple order
#   details associated with it.
# - `has_many :orders, through: :order_details`: Sets up a many-to-many relationship
#   where products can be accessed through the associated order details.
# - `has_many :historical_prices`: Indicates that each product can have multiple
#   historical price records.
# - `has_one_attached :image`: Allows each product to have a single attached image
#   for visual representation.
#
# Validations:
# - `validates :name, presence: true`: Ensures that each product has a name.
# - `validates :description, presence: true`: Ensures that each product has a description.
# - `validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }`:
#   Ensures that the price is present and is a non-negative number.
# - `validates :stock, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }`:
#   Ensures that the stock is present, is an integer, and is a non-negative number.
#
# Scopes:
# - `search_by_keyword`: Filters products by name or description matching the given
#   keyword. Useful for implementing search functionality.
# - `on_sale`: Filters products with a price of 15 or less, indicating they are on sale.
# - `new_products`: Filters products created within the last 2 days, identifying new
#   arrivals.
#
# Class Methods:
# - `self.ransackable_associations`: Returns an array of associations that can be
#   used for searching and filtering with Ransack. This includes `category`,
#   `historical_prices`, `order_details`, and `orders`.
# - `self.ransackable_attributes`: Returns an array of attributes that can be used
#   for searching and filtering with Ransack. This includes `id`, `name`, `description`,
#   `price`, `stock`, `category_id`, `created_at`, and `updated_at`.
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_details, dependent: :destroy
  has_many :orders, through: :order_details
  has_many :historical_prices, dependent: :destroy

  has_one_attached :image

  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :stock, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  scope :search_by_keyword, lambda { |keyword|
    where("name LIKE :keyword OR description LIKE :keyword", keyword: "%#{keyword}%")
  }

  scope :on_sale, -> { where(price: ...15) }

  scope :new_products, -> { where(created_at: 2.days.ago..) }

  def self.ransackable_associations(_auth_object = nil)
    %w[category historical_prices order_details orders]
  end

  def self.ransackable_attributes(_auth_object = nil)
    %w[id name description price stock category_id created_at updated_at]
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

# ProductsController manages the display and filtering of products for users.
# It allows users to view all products, filter them by category, search by keyword,
# and see specific product details. It also provides views for products on sale
# and new arrivals.
class ProductsController < ApplicationController
  # Displays a paginated list of products. Supports filtering by search keyword
  # and category. If search parameters are present, the list will be filtered
  # accordingly. Pagination is set to display 10 products per page.
  def index
    @products = Product.all
    @products = @products.search_by_keyword(params[:search]) if params[:search].present?
    @products = @products.where(category_id: params[:category_id]) if params[:category_id].present?
    @products = @products.page(params[:page]).per(10)
  end

  # Displays a paginated list of products that belong to a specific category.
  # The category is identified by the category ID passed as a parameter.
  # Pagination is set to display 10 products per page.
  def by_category
    @category = Category.find(params[:id])
    @products = @category.products.page(params[:page]).per(10)
  end

  # Displays the details of a single product identified by the product ID
  # passed as a parameter.
  def show
    @product = Product.find(params[:id])
  end

  # Displays a paginated list of products that are currently on sale.
  # Pagination is set to display 10 products per page.
  def on_sale
    @products = Product.on_sale.page(params[:page]).per(10)
  end

  # Displays a paginated list of newly arrived products.
  # Pagination is set to display 10 products per page.
  def new_products
    @products = Product.new_products.page(params[:page]).per(10)
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

# The ProductsHelper module is designed to include helper methods that
# assist with the display and management of product-related content within
# views. These methods can simplify tasks such as formatting product details,
# generating product-specific links, and displaying product information.
#
# Example usage might include methods for formatting product prices,
# generating product images, or displaying product ratings and reviews.
module ProductsHelper
end

app/views/products/by_category.html.erb
<h1>Products in <%= @category.name %></h1>
<%= link_to 'Home', root_path %>
<div>
  <% @products.each do |product| %>
    <div>
      <h2><%= link_to product.name, product_path(product) %></h2>
      <p><%= product.description %></p>
      <p>Price: <%= product.price %></p>
      <%= image_tag url_for(product.image), size: "100x100" if product.image.attached? %>
    </div>
  <% end %>
</div>

<%= paginate @products %>

app/views/products/index.html.erb
<h1>All Products</h1>
<%= link_to 'Home', root_path %>

<%= form_with(url: products_path, method: "get") do |form| %>
  <%= form.text_field :search, placeholder: "Search by keyword" %>
  <%= form.collection_select :category_id, Category.all, :id, :name, prompt: "Select a category" %>
  <%= form.submit "Search" %>
<% end %>

<div>
  <%= link_to 'Show On Sale Products', on_sale_products_path %><br>
  <%= link_to 'Show New Products', new_products_path %>
</div>

<div>
  <% @products.each do |product| %>
    <div>
      <h2><%= link_to product.name, product_path(product) %></h2>
      <p><%= product.description %></p>
      <p>Price: <%= product.price %></p>
      <%= image_tag url_for(product.image), size: "100x100" if product.image.attached? %>
    </div>
  <% end %>
</div>

<%= paginate @products %>

app/views/products/new_products.html.erb
<h1>New Products</h1>
<%= link_to 'Home', root_path %>

<div>
  <% @products.each do |product| %>
    <div>
      <h2><%= link_to product.name, product_path(product) %></h2>
      <p><%= product.description %></p>
      <p>Price: <%= product.price %></p>
      <%= image_tag url_for(product.image), size: "100x100" if product.image.attached? %>
    </div>
  <% end %>
</div>

<%= paginate @products %>

app/views/products/on_sale.html.erb
<h1>Products On Sale</h1>
<%= link_to 'Home', root_path %>

<div>
  <% @products.each do |product| %>
    <div>
      <h2><%= link_to product.name, product_path(product) %></h2>
      <p><%= product.description %></p>
      <p>Price: <%= product.price %></p>
      <%= image_tag url_for(product.image), size: "100x100" if product.image.attached? %>
    </div>
  <% end %>
</div>

<%= paginate @products %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<%= link_to 'Home', root_path %>

<div>
  <h2>Description</h2>
  <p><%= @product.description %></p>

  <h2>Price</h2>
  <p><%= @product.price %></p>

  <h2>Stock</h2>
  <p><%= @product.stock %></p>

  <h2>Category</h2>
  <p><%= @product.category.name %></p>

<%= form_with url: add_product_cart_path(@product.id), method: :post, local: true do |form| %>
  <%= form.hidden_field :product_id, value: @product.id %>
  <%= form.label :quantity, "quantity" %>
  <%= form.number_field :quantity, value: 1, min: 1, max: 5 %>
  <%= form.submit 'Add to the  Cart' %>
<% end %>

  <h2>Image</h2>
  <%= image_tag url_for(@product.image), size: "300x300" if @product.image.attached? %>
</div>